### ISSUE TITLE
don't ignore arguments with data kinds

### ISSUE THREAD

**Issue by nfrisby** [RyanGlScott/th-lift#20]
The current code includes the comment

```
-- Only consider *-kinded type variables, because Lift instances cannot
-- meaningfully be given to types of other kinds.
```

This comment is explaining how the splice constructs the instance context. It's a reasonable compromise, but it rules out something like the following:

```
data F (b :: Bool) = MkF (If b Float Double)
$(deriveLift ''F)
```

Currently that splice will fail to compile, because it simply ignores `b`. With this Issue, I request that it instead generate something like the following:

```
instance Lift (If b Float Double) => Lift (F b)
```

In particular, a very robust solution would be to generate a context containing `(Lift T0, Lift T1, ...)` where each `Tn` is the type of one of the data type's constructors' arguments. The downside is that such a naive (but general!) context would be quite noisy and often include redundancies. So perhaps only fallback to this approach for constructor arguments that include an occurrence of a non-`*` type argument.

**Comment by RyanGlScott** [comment]
I would _love_ to have something like this, but to be honest, I really don't see it being feasible to implement unless you have full access to the GHC typechecker. If you generate a context like `(Lift T0, Lift T1, ...)`, it opens up a huge can of worms. One thing that bothers me is if you had something like this:

```haskell
newtype List a = List [a]
$(deriveLift ''List)
```

Then the spliced instance would be `instance Lift [a] => Lift (List a)`. This is not a good thing IMO, since (1) you now have to enable `FlexibleContexts` and `UndecidableInstances` for your code to compile, and (2) you have to squint to see that the context really only requires `Lift a`.

A clever TH hacker could use `reifyInstances` on `Lift` to discover that the `Lift [a]` instance only requires a `Lift a` constraint, but then you'd have to watch out for mutually recursive data declarations, e.g.,

```haskell
data Foo a = Foo (Bar a)
data Bar a = Bar (Foo a)
$(deriveLift ''Foo)
$(deriveLift ''Bar)
```

since their `Lift` instances would be available to `reifyInstances` at splice time.

It _might_ possible to emulate GHC's built-in deriving mechanism with enough elbow grease, but the more I've thought about it, the more I've concluded that it simply isn't worth implementing, especially when you already have #21. Perhaps I'm being too pessimistic, though. @mboes, what do you think?

**Comment by nfrisby** [comment]
I completely agree that the contexts would be onerous in various ways. But
do note that I suggested only doing this for arguments with kind other than
star; the common cases that don't need this would continue to behave as
they currently do.

Also, very low priority because of `makeLift` / #21.

**Comment by mboes** [comment]
I'm loath to do this, mainly because this has the potential to add a fair amount of complexity and unintended consequences, as @RyanGlScott points out, when by GHC 8.0 we'll have `-XDeriveLift` anyways. For instance, what happens to `data T (a :: Bool) b = T (F a b)` where `F a b ~ Int`? The purely syntactic approach of th-lift is rather limiting compared to what GHC can do. But not opposed to a patch.

I think the strategy that @RyanGlScott came up with recently, which consists in saying "simple and predictable instances for simple data types, manual instance contexts for exotic ones", is a good approach. It's a reasonable (small) price to pay for exotic types.

**Comment by chrisdone** [comment]
> by GHC 8.0 we'll have `-XDeriveLift` anyways

That’s a thing? 😲
